vscode:
  extensions:
    - aaron-bond.better-comments,
    - abusaidm.html-snippets
    - adam-watters.vscode-color-pick
    - ardenivanov.svelte-intellisense
    - austenc.tailwind-docs
    - azemoh.one-monokai
    - bbenoist.Doxygen
    - bodil.prettier-toml
    - bradlc.vscode-tailwindcss
    - bungcip.better-toml
    - christian-kohler.npm-intellisense
    - christian-kohler.path-intellisense
    - chrmarti.regex
    - cschlosser.doxdocgen
    - Dart-Code.dart-code
    - dbaeumer.vscode-eslint
    - denoland.vscode-deno
    - dracula-theme.theme-dracula
    - dzhavat.css-flexbox-cheatsheet
    - eamodio.gitlens
    - ecmel.vscode-html-css
    - EditorConfig.EditorConfig
    - EmilijanMB.sublime-text-4-theme
    - emmanuelbeziat.vscode-great-icons
    - esbenp.prettier-vscode
    - fabiospampinato.vscode-diff
    - firefox-devtools.vscode-firefox-debug
    - fivethree.vscode-svelte-snippets
    - foxundermoon.shell-format
    - franneck94.c-cpp-runner
    - GitHub.copilot
    - GitHub.github-vscode-theme
    - gitpod.gitpod-desktop
    - GrapeCity.gc-excelviewer
    - GraphQL.vscode-graphql
    - GraphQL.vscode-graphql-execution
    - GraphQL.vscode-graphql-syntax
    - icrawl.discord-vscode
    - jamesmaj.easy-icons
    - jdinhlife.gruvbox
    - jeff-hykin.better-cpp-syntax
    - kuscamara.electron
    - luniclynx.bison
    - luniclynx.lex
    - matangover.mypy
    - mdickin.markdown-shortcuts
    - mikestead.dotenv
    - mohsen1.prettify-json
    - ms-azuretools.vscode-docker
    - ms-dotnettools.csharp
    - ms-ossdata.vscode-postgresql
    - ms-python.isort
    - ms-python.python
    - ms-python.vscode-pylance
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-vscode-remote.remote-containers
    - ms-vscode-remote.remote-ssh
    - ms-vscode-remote.remote-ssh-edit
    - ms-vscode-remote.remote-wsl
    - ms-vscode.cmake-tools
    - ms-vscode.cpptools
    - ms-vscode.cpptools-extension-pack
    - ms-vscode.cpptools-themes
    - ms-vscode.powershell
    - ms-vscode.remote-explorer
    - ms-vscode.vscode-typescript-next
    - ms-vscode.vscode-typescript-tslint-plugin
    - ms-vsliveshare.vsliveshare
    - mvllow.rose-pine
    - naumovs.color-highlight
    - ngtystr.ppm-pgm-viewer-for-vscode
    - njpwerner.autodocstring
    - Perkovec.emoji
    - PKief.material-icon-theme
    - Prisma.prisma
    - radu-matei.vscode-ubuntu-color-theme
    - redhat.java
    - redhat.vscode-yaml
    - ritwickdey.LiveServer
    - rogalmic.bash-debug
    - rpinski.shebang-snippets
    - rust-lang.rust-analyzer
    - rvest.vs-code-prettier-eslint
    - ryu1kn.partial-diff
    - sainnhe.gruvbox-material
    - shakram02.bash-beautify
    - shardulm94.trailing-spaces
    - shd101wyy.markdown-preview-enhanced
    - SolarLiner.linux-themes
    - streetsidesoftware.code-spell-checker
    - svelte.svelte-vscode
    - syler.sass-indented
    - tetradresearch.vscode-h2o
    - tomoki1207.pdf
    - twxs.cmake
    - vadimcn.vscode-lldb
    - VisualStudioExptTeam.intellicode-api-usage-examples
    - VisualStudioExptTeam.vscodeintellicode
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-pack
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
    - william-voyek.vscode-nginx
    - yzane.markdown-pdf
    - ZainChen.json
    - zhuangtongfa.material-theme