vscode:
  extensions:
    - aaron-bond.better-comments,
    - abusaidm.html-snippets
    - adam-watters.vscode-color-pick
    - austenc.tailwind-docs
    - bradlc.vscode-tailwindcss
    - christian-kohler.npm-intellisense
    - christian-kohler.path-intellisense
    - dbaeumer.vscode-eslint
    - dzhavat.css-flexbox-cheatsheet
    - ecmel.vscode-html-css
    - EditorConfig.EditorConfig
    - emmanuelbeziat.vscode-great-icons
    - esbenp.prettier-vscode
    - GitHub.copilot
    - kuscamara.electron
    - mdickin.markdown-shortcuts
    - ms-vscode-remote.remote-containers
    - ms-vscode-remote.remote-ssh
    - ms-vscode.remote-explorer
    - ms-vscode.vscode-typescript-next
    - ms-vscode.vscode-typescript-tslint-plugin
    - naumovs.color-highlight
    - PKief.material-icon-theme
    - redhat.vscode-yaml
    - rvest.vs-code-prettier-eslint
    - shardulm94.trailing-spaces
    - syler.sass-indented
    - VisualStudioExptTeam.intellicode-api-usage-examples
    - VisualStudioExptTeam.vscodeintellicode
    - ZainChen.json
    - zhuangtongfa.material-theme

tasks:
  - init: npm install
    command: |
      export HMR_HOST="`gp url 3000`
      npm run build
ports:
  - port: 3000
    onOpen: open-browser
